const BINGO_CONFIG = {
  supabaseUrl: "",
  supabaseAnonKey: "",
  "settings": {
    "theme": "dark",
    "accentColor": "#89b4fa"
  },
  "words": [
  "Algolia",
  "Review",
  "Bulksale",
  "Soft-Bundling",
  "Stagetest",
  "ElMare Monolog",
  "Sams Kamera funktioniert",
  "\"You're on mute!\" 🤫",
  "Let's talk about... Sexuelle Anspielungen 🎶",
  "Paulanergarten-Story 🍺",
  "Daily Overkill 💀 (> 30 Min)",
  "Close Call ⏱️ (29-30 Min)",
  "2 Fast 2 Furious 🏎️ (< 10 Min)",
  "KI-Talk",
  "Die Da Oben",
  "Cyber-Voice 🤖",
  "Fur-baby Invasion",
  "Folge-Meeting hat angefangen",
  "Stranger Cameo 👥",
  "Deep Dive Dilemma",
  "The Flex-Zone 💪 - „Weird flex but okay“",
  "Freezer 🧊",
  "Forced DC 🔌 (Error 404)",
  "Legacy-Rant 🦖",
  "Rubberducking Live 🦆",
  "CEO-Invasion 👑",
  "Dark Mode Resident 🕶️",
  "Arakel Monolog",
  "Need to Restart",
  "Updates sucks",
  "Refactoring",
  "Deploy"
]
};